spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/react_project
    username: root
    password: dongnguyen190699
  jpa:
    show-sql: true

  security:
    cors:
      allowed-origins: '*'
      allowed-methods: '*'
      allowed-headers: '*'
      exposed-headers: 'Authorization,Link,X-Total-Count'
      allow-credentials: true
      max-age: 1800
